import { Providers } from "./providers";

import { fetchCommerce } from "@/lib/services/fetchers";

import SiteHeader from "@/components/layout/SiteHeader";
import SiteFooter from "@/components/layout/SiteFooter";

export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await fetchCommerce();

  return (
    <html lang="en">
      <body>
        <Providers>
          <SiteHeader categories={categories} />
          <main>{children}</main>
          <SiteFooter />
        </Providers>
      </body>
    </html>
  );
}
